"""initial schema

Revision ID: 204377234d9c
Revises: 
Create Date: 2026-04-15 18:15:38.504798

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '204377234d9c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('digests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('period', sa.String(length=20), nullable=False),
    sa.Column('region', sa.String(length=40), nullable=False),
    sa.Column('category_filter', sa.String(length=200), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.Column('content_md', sa.Text(), nullable=False),
    sa.Column('source_document_ids_json', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('digests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_digests_period'), ['period'], unique=False)
        batch_op.create_index(batch_op.f('ix_digests_region'), ['region'], unique=False)

    op.create_table('sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=200), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('region', sa.String(length=200), nullable=False),
    sa.Column('language', sa.String(length=200), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=False),
    sa.Column('scrape_strategy', sa.String(length=50), nullable=False),
    sa.Column('feeds_json', sa.JSON(), nullable=True),
    sa.Column('list_selector', sa.String(length=500), nullable=True),
    sa.Column('link_selector', sa.String(length=500), nullable=True),
    sa.Column('custom_scraper', sa.String(length=200), nullable=True),
    sa.Column('polling_cadence', sa.String(length=50), nullable=True),
    sa.Column('min_poll_interval_seconds', sa.Integer(), nullable=False),
    sa.Column('last_polled_at', sa.DateTime(), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sources', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sources_active'), ['active'], unique=False)
        batch_op.create_index(batch_op.f('ix_sources_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_sources_priority'), ['priority'], unique=False)
        batch_op.create_index(batch_op.f('ix_sources_slug'), ['slug'], unique=True)

    op.create_table('topics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('name_en', sa.String(length=200), nullable=False),
    sa.Column('name_ar', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['topics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('topics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_topics_slug'), ['slug'], unique=True)

    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('canonical_url', sa.String(length=2000), nullable=False),
    sa.Column('dedupe_hash', sa.String(length=64), nullable=False),
    sa.Column('document_type', sa.String(length=40), nullable=False),
    sa.Column('title', sa.String(length=1000), nullable=False),
    sa.Column('title_ar', sa.String(length=1000), nullable=True),
    sa.Column('authors_json', sa.JSON(), nullable=True),
    sa.Column('abstract', sa.Text(), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('language', sa.String(length=20), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.Column('pdf_path', sa.String(length=1000), nullable=True),
    sa.Column('html_path', sa.String(length=1000), nullable=True),
    sa.Column('analysis_status', sa.String(length=20), nullable=False),
    sa.Column('raw_metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_documents_analysis_status'), ['analysis_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_canonical_url'), ['canonical_url'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_dedupe_hash'), ['dedupe_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_documents_document_type'), ['document_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_published_at'), ['published_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_source_id'), ['source_id'], unique=False)
        batch_op.create_index('ix_documents_status_published', ['analysis_status', 'published_at'], unique=False)

    op.create_table('ingest_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('strategy', sa.String(length=50), nullable=True),
    sa.Column('documents_found', sa.Integer(), nullable=False),
    sa.Column('documents_new', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ingest_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ingest_runs_source_id'), ['source_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ingest_runs_started_at'), ['started_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_ingest_runs_status'), ['status'], unique=False)

    op.create_table('analyses',
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('prompt_variant', sa.String(length=40), nullable=False),
    sa.Column('thesis', sa.Text(), nullable=True),
    sa.Column('key_points_json', sa.JSON(), nullable=True),
    sa.Column('evidence_type', sa.String(length=40), nullable=True),
    sa.Column('methodology', sa.Text(), nullable=True),
    sa.Column('frameworks_json', sa.JSON(), nullable=True),
    sa.Column('regions_json', sa.JSON(), nullable=True),
    sa.Column('topics_json', sa.JSON(), nullable=True),
    sa.Column('actors_json', sa.JSON(), nullable=True),
    sa.Column('counterarguments', sa.Text(), nullable=True),
    sa.Column('limitations', sa.Text(), nullable=True),
    sa.Column('implications', sa.Text(), nullable=True),
    sa.Column('ar_summary', sa.Text(), nullable=True),
    sa.Column('en_summary', sa.Text(), nullable=True),
    sa.Column('key_quotes_json', sa.JSON(), nullable=True),
    sa.Column('extras_json', sa.JSON(), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('prompt_version', sa.String(length=20), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('document_id')
    )
    with op.batch_alter_table('analyses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_analyses_prompt_variant'), ['prompt_variant'], unique=False)

    op.create_table('document_topics',
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('document_id', 'topic_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('document_topics')
    with op.batch_alter_table('analyses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_analyses_prompt_variant'))

    op.drop_table('analyses')
    with op.batch_alter_table('ingest_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ingest_runs_status'))
        batch_op.drop_index(batch_op.f('ix_ingest_runs_started_at'))
        batch_op.drop_index(batch_op.f('ix_ingest_runs_source_id'))

    op.drop_table('ingest_runs')
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_index('ix_documents_status_published')
        batch_op.drop_index(batch_op.f('ix_documents_source_id'))
        batch_op.drop_index(batch_op.f('ix_documents_published_at'))
        batch_op.drop_index(batch_op.f('ix_documents_document_type'))
        batch_op.drop_index(batch_op.f('ix_documents_dedupe_hash'))
        batch_op.drop_index(batch_op.f('ix_documents_canonical_url'))
        batch_op.drop_index(batch_op.f('ix_documents_analysis_status'))

    op.drop_table('documents')
    with op.batch_alter_table('topics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_topics_slug'))

    op.drop_table('topics')
    with op.batch_alter_table('sources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sources_slug'))
        batch_op.drop_index(batch_op.f('ix_sources_priority'))
        batch_op.drop_index(batch_op.f('ix_sources_category'))
        batch_op.drop_index(batch_op.f('ix_sources_active'))

    op.drop_table('sources')
    with op.batch_alter_table('digests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_digests_region'))
        batch_op.drop_index(batch_op.f('ix_digests_period'))

    op.drop_table('digests')
    # ### end Alembic commands ###
