-- =====================================================================
-- Backfill fix: make depth_sources.id and depth_documents.id into
-- identity columns on databases that were created from the initial
-- migration before it declared identity.
--
-- Safe to run on a fresh DB too (idempotent via the `if not exists`
-- guards in Postgres 16+ — we check for column_default first).
-- =====================================================================

do $$
begin
  if (select column_default is null
      from information_schema.columns
      where table_schema = 'public'
        and table_name = 'depth_sources'
        and column_name = 'id') then
    execute 'alter table public.depth_sources
             alter column id add generated by default as identity';
  end if;
end $$;

do $$
begin
  if (select column_default is null
      from information_schema.columns
      where table_schema = 'public'
        and table_name = 'depth_documents'
        and column_name = 'id') then
    execute 'alter table public.depth_documents
             alter column id add generated by default as identity';
  end if;
end $$;

-- Advance both sequences past the highest existing id so the next
-- auto-assigned id doesn't collide with the SQLite-migrated rows.
select setval(
  pg_get_serial_sequence('public.depth_sources', 'id'),
  coalesce((select max(id) from public.depth_sources), 0) + 1,
  false
);

select setval(
  pg_get_serial_sequence('public.depth_documents', 'id'),
  coalesce((select max(id) from public.depth_documents), 0) + 1,
  false
);
